parameters:
#    sg_parametricos.example.class: SG\ParametricosBundle\Example

services:
#    sg_parametricos.example:
#        class: %sg_parametricos.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
