<?php

namespace SG\UsuariosBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * DatosMedicosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DatosMedicosRepository extends EntityRepository
{
}